version: '3.8'

services:
  db:
    container_name: psql_database_dev
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialapp
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    container_name: psql_pgadmin_dev
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend

  api:
    container_name: asgi_uvicorn_dev
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: backend